---
title: Accessing & managing financial data
---

**Exercises:**

1. Read the book chapters [Accessing & managing financial data](https://www.tidy-finance.org/r/accessing-and-managing-financial-data.html) and [WRDS, CRSP, and Compustat](https://www.tidy-finance.org/r/wrds-crsp-and-compustat.html) entirely. If you prefer to read Python code, the chapters are available [here](https://www.tidy-finance.org/python/accessing-and-managing-financial-data.html) and [here](https://www.tidy-finance.org/python/wrds-crsp-and-compustat.html). They may contain some advanced concepts but also a description of almost every important dataset relevant to research in empirical finance. To get more information on how to compute returns adjusted for delisting, follow the procedure described in Chapter 7.2 of the book *Empirical Asset Pricing*.

3. Download the file `crsp_monthly.parquet` from Absalon. Store it in the folder called `data-r` (`data-python`) within your standard working directory for the course. Almost all exercises from now on will start with reading data out of this file, so make sure you familiarize yourself with this short *minimal setup to load data into your R or Python session memory from a fresh session* (you can consult it anytime again later during the course). 

::: {.panel-tabset group="language"}
## Python

```{python}
#| eval: false
import pandas as pd
pd.read_parquet("data-python/crsp_monthly.parquet")
```

## R

```{r}
#| eval: false
library(arrow)
crsp_monthly <- read_parquet("data-r/crsp_monthly.parquet")
``` 

:::

4. If you need help with .parquet files, post your question on Absalon. Your TA, your peers, and I will help you!
5. Replicate the following two figures provided in the lecture slides: i) Create a time series of the number of stocks in the CRSP sample, which are listed on NASDAQ, NYSE, and AMEX. ii) Illustrate the time series of total market values (inflation-adjusted) based on industry classification `siccd`. The book *Empirical Asset Pricing* (Bali, Murrey, and Engle) provides a detailed walk-through if you need help.

**Solutions:** 
All solutions are provided in the book chapter *WRDS, CRSP, and Compustat* ([R version](https://www.tidy-finance.org/r/wrds-crsp-and-compustat.html) and [Python version](https://www.tidy-finance.org/python/wrds-crsp-and-compustat.html)) and the lecture slides.
