#!/usr/bin/env Rscript
# Copies the rendered lecture decks from the sibling course-repository into
# slides/ and (re)generates the embedded Slides page (slides.qmd).
#
# Wired as a Quarto pre-render hook (see _quarto.yml), so it runs automatically
# on every `quarto render` / `quarto preview`. The decks are treated as opaque,
# already-rendered, self-contained HTML -- nothing here executes R/Python.

source_dir <- Sys.getenv("SLIDES_SRC", "../course-repository/lecture-slides")
dest_dir   <- "slides"
out_qmd    <- "slides.qmd"

if (!dir.exists(source_dir)) {
  stop(sprintf("Source slides folder not found: %s", normalizePath(source_dir, mustWork = FALSE)))
}

# Fresh copy of the decks (drop stale ones that no longer exist upstream).
if (dir.exists(dest_dir)) {
  old <- list.files(dest_dir, pattern = "\\.html$", full.names = TRUE)
  if (length(old)) invisible(file.remove(old))
} else {
  dir.create(dest_dir, recursive = TRUE)
}

decks <- sort(list.files(source_dir, pattern = "\\.html$"))
if (length(decks) == 0) stop(sprintf("No .html decks found in %s", source_dir))
invisible(file.copy(file.path(source_dir, decks), file.path(dest_dir, decks), overwrite = TRUE))
cat(sprintf("Copied %d deck(s) to %s\n", length(decks), dest_dir))

# Capitalise each word (matches the previous generator's titles).
title_case <- function(s) {
  w <- strsplit(s, " ", fixed = TRUE)[[1]]
  paste(toupper(substring(w, 1, 1)), substring(w, 2), sep = "", collapse = " ")
}

# Turn a filename stem into a readable heading.
deck_title <- function(stem) {
  s <- sub("^aef-", "", stem)
  m <- regmatches(s, regexec("^([0-9]+)-(.*)$", s))[[1]]
  if (length(m) == 3) return(paste0("Lecture ", m[2], " &mdash; ", title_case(gsub("-", " ", m[3]))))
  m2 <- regmatches(s, regexec("^mandatory-assignment-([0-9]+)-evaluation$", s))[[1]]
  if (length(m2) == 2) return(paste0("Mandatory Assignment ", m2[2], " &mdash; Evaluation"))
  title_case(gsub("-", " ", s))
}

lines <- c(
  "---",
  "title: Slides",
  "---",
  "",
  "<!-- GENERATED by tools/build-slides-page.R -- do not edit by hand. -->",
  "",
  "Each lecture deck is embedded below. Click a deck and use its own controls",
  "(or the arrow keys) to navigate, open it full screen, or download it.",
  ""
)

for (f in decks) {
  stem  <- sub("\\.html$", "", f)
  title <- deck_title(stem)
  src   <- paste0("slides/", f)
  lines <- c(lines,
    sprintf("## %s {#%s}", title, stem),
    "",
    "::: {.ratio .ratio-16x9 .slide-embed}",
    "```{=html}",
    sprintf('<iframe src="%s" title="%s" loading="lazy" allowfullscreen></iframe>', src, title),
    "```",
    ":::",
    "",
    "```{=html}",
    sprintf('<a class="btn btn-sm btn-outline-primary" href="%s" target="_blank" rel="noopener">Open full screen &#8599;</a>', src),
    sprintf('<a class="btn btn-sm btn-outline-secondary" href="%s" download>Download &#8595;</a>', src),
    "```",
    ""
  )
}

lines <- c(lines,
  "```{=html}",
  "<style>",
  "  .slide-embed { border: 1px solid var(--bs-border-color); border-radius: .375rem; overflow: hidden; margin-bottom: .5rem; }",
  "  .slide-embed iframe { width: 100%; height: 100%; border: 0; }",
  "</style>",
  "```"
)

writeLines(lines, out_qmd)
cat(sprintf("Wrote %s\n", out_qmd))
